name: Create Branch Workflow

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'Name of the new branch'
        required: true

  pull_request:
    branches:
      - main

jobs:
  create_branch:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Determine Branch Name
      id: determine_branch_name
      run: |
        echo "branch_name=${{ github.event.inputs.branch_name }}" >> $GITHUB_ENV
      if: ${{ github.event_name == 'workflow_dispatch' }}
      
    - name: Determine Branch Name for PR to main
      id: determine_pr_branch_name
      run: |
        echo "branch_name=${{ github.head_ref }}" >> $GITHUB_ENV
      if: ${{ github.event_name == 'pull_request' && github.base_ref == 'main' }}

    - name: Skip Create Branch if name contains '-ai-recommender'
      id: skip_create_branch
      run: |
        if [[ "${{ env.branch_name }}" == *"-ai-recommender"* ]]; then
          echo "Skipping Create Branch step"
          exit 1
        fi
      continue-on-error: true

    - name: Create Branch
      if: steps.skip_create_branch.outcome == 'success'
      uses: daffahilmyf/create-branch-action@main
      with:
        branch_name: ${{env.branch_name}}
        token: ${{ secrets.GH_TOKEN }}
        openai_key: "openai_key"
        program_folder_base_path: "./program"
        test_folder_base_path: "./tests"
        assistant_id: "assistant_id"
